server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://192.168.*.*:*"
              - "http://10.*.*.*:*"
              - "exp://*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: http://localhost:1290
          predicates:
            - Path=/football-pool/v1/api/auth/**
          filters:
            - PreserveHostHeader
        # - id: companies
        #   uri: http://localhost:1090
        #   predicates:
        #     - Path=/widget_ai/v1/api/companies/**
        # - id: candidate
        #   uri: http://localhost:1190
        #   predicates:
        #     - Path=/widget_ai/v1/api/candidates/**
        # - id: login
        #   uri: http://localhost:1290
        #   predicates:
        #     - Path=/widget_ai/v1/api/login
        # - id: job
        #   uri: http://localhost:1390
        #   predicates:
        #     - Path=/widget_ai/v1/api/jobs/**
        # - id: interviews
        #   uri: http://localhost:1490
        #   predicates:
        #     - Path=/widget_ai/v1/api/interviews/**